# Generated by Django 5.0.3 on 2024-04-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
