# Generated by Django 5.0.3 on 2024-04-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
