# Generated by Django 5.0.3 on 2024-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default='0', null=True, verbose_name='phone_number'),
        ),
    ]
