# Generated by Django 5.0.3 on 2024-04-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_line_eight_invoice_line_eight_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_eight',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 8'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_eight_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_eight_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_eight_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 5'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_five_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 4'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_four_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 9'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_nine_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_one_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 7'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_seven_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 6'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_six_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 10'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_ten_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 3'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_three_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Item 2'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_total_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_two_unit_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='U.Price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default='0', null=True, verbose_name='Phone Number'),
        ),
    ]
